name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Log into the Docker registry
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

      # Push the built Docker image to the registry
    - name: Push Docker image
      run: |
        REGISTRY=$(echo "${{ env.REGISTRY }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
        docker load -i ./docker-result
        IMAGE_ID=$(docker images --format '{{.ID}}' | head -n 1)
        docker tag ${IMAGE_ID} ${REGISTRY}/${IMAGE_NAME}:latest
        docker push ${REGISTRY}/${IMAGE_NAME}:latest
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME}}
        REGISTRY: ${{ env.REGISTRY}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
